### ISSUE TITLE
GraalVM 20.3.0

### ISSUE THREAD

**Issue by mike-neck** [mike-neck/graalvm-native-image-plugin#100]
Changing target GraalVM version.

- out: 20.2.0
- new: 20.3.0

**Comment by sne11ius** [comment]
Hey. Thanks for fixing #98 :D
With the new version, I get a different error:
```
Execution failed for task ':mergeNativeImageConfig'.
> org.mikeneck.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<org.mikeneck.graalvm.config.ResourceUsage>` out of START_OBJECT token
   at [Source: (BufferedReader); line: 2, column: 15] (through reference chain: org.mikeneck.graalvm.config.ResourceConfig["resources"])
```
It seems my `resource-config.json` has a slightly different format. Please see the attached file.
[resource-config.json.txt](https://github.com/mike-neck/graalvm-native-image-plugin/files/5649690/resource-config.json.txt)

**Comment by mike-neck** [comment]
Thanks for your report.

It seems the format of `resource-config.json` in 2020.3.0 has been changed from one in 2020.2.x.
https://www.graalvm.org/reference-manual/native-image/Resources/
Thus your json has no problem. The problem is that this plugin does not support new format.

Work around: would you manually apply configuration json files? This plugin provides `arguments` option to offer parameters to GraalVM.

**Comment by sne11ius** [comment]
Hey. Thanks for the heads up. I'm now "manually"creating the resource configs and everything works fine.
... and thanks.foe making the plugin :)

**Comment by mike-neck** [comment]
By #103 we can process the new format of resource-config.json.
