### ISSUE TITLE
Add support for JVM arguments

### ISSUE THREAD

**Issue by guidota** [mike-neck/graalvm-native-image-plugin#115]
When running generateNativeImageConfig task, I need to provide some JVM arguments to run application properly.
JVM arguments need to be place before the application arguments, that's why adding them as arguments is useless.

I'm trying to run something like this:

```
generateNativeImageConfig {
    enabled = true
    byRunningApplication {
        if(os.isMacOsX) {
            arguments("-XstartOnFirstThread")
        }
        arguments("once")
    }
}
```
Without this argument `-XstartOnFirstThread` my application won't start and never generate the config files.

I tried executing it manually from command line and it works fine, so what I expect is to run my application within my JVM arguments well placed.
If I have time, will try to submit a proposal.

**Comment by mike-neck** [comment]
This feature will be available in version 1.1.0 of this plugin.

You can configure jvm arguments as bellow.

https://github.com/mike-neck/graalvm-native-image-plugin/blob/63f13f66a482ea13e1c9911e5bed5afdd8c06c1d/src/functionalTest/resources/case-115-jvm-args/build-gradle-kts.txt#L23-L30
