### ISSUE TITLE
I run installNativeImage but it can not generate 

### ISSUE THREAD

**Issue by zhoufeilongjava** [mike-neck/graalvm-native-image-plugin#122]
here is my config

`
nativeImage {
    graalVmHome = System.getProperty('java.home')
    mainClass = 'demo.Server'
    executableName = 'io3-application'
    outputDirectory = '/native-image'
}

generateNativeImageConfig {
    enabled = true
    byRunningApplicationWithoutArguments()
}
`

**Comment by mike-neck** [comment]
Would you provide more detail log?
The description you wrote is not enough for me to do any action.

There is a format to report bugs so please fill items here https://github.com/mike-neck/graalvm-native-image-plugin/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by zhoufeilongjava** [comment]
hi,I supplement detail.@mike-neck

Describe What happened
===

A clear and concise description of what the bug is.

How To Reproduce
===

Steps to reproduce the behavior:

1. What did you wish to do?
---
generate native image

2. How did you configure build? Add your `build.gradle` file(or other `gradle` build files) .
---
`plugins {
    id 'java'
    id "org.mikeneck.graalvm-native-image" version "1.2.0"
}

group 'printer-service-3.0'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'io.vertx:vertx-mqtt:4.0.0'
    compile 'io.vertx:vertx-redis-client:4.0.0'
    compile 'redis.clients:jedis:2.9.0'
    compile 'io.vertx:vertx-mysql-client:4.0.0'
    compile 'org.msgpack:msgpack-core:0.8.16'
    compile 'log4j:log4j:1.2.17'
    compile 'org.slf4j:slf4j-log4j12:1.7.19'
    compile 'org.apache.commons:commons-lang3:3.5'
    compileOnly('org.projectlombok:lombok:1.18.4')
    compile('com.gunma:printer-template-render-sdk:2.0.0')
    compile 'com.gunma.printevent:event:1.0.7'
    compile('com.gunma:sms-client:1.0.129')
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

configurations.all {
    exclude group: 'ch.qos.logback', module: 'logback-classic'
    exclude group: 'ch.qos.logback', module: 'logback-core'
}

nativeImage {
    graalVmHome = System.getProperty('java.home')
    mainClass = 'com.gunma.io.Server'
    executableName = 'io3-application'
    outputDirectory = '/native-image'
}

generateNativeImageConfig {
    enabled = true
    byRunningApplicationWithoutArguments()
}`


3. What task did you run?
---
./gradlew installNativeImage --stacktrace

4. What is an error or exception?
---
no error,build success

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
1 actionable task: 1 up-to-date

- OS: MacOS X 10.14.5
- Plugin Version : 1.2.0
- Gradle Version 6.7.1
- Java Version:GraalVM EE 21.0.0

**Comment by mike-neck** [comment]
You should run `./gradlew nativeImage` instead of running `./gradlew installNativeImage`.

The task `installNativeImage` is a task to install `native-image` command into your gaalvm's `bin` directory, which is a wrapper task of `gu` command, so that this task does not generate any native binaries.

**Comment by zhoufeilongjava** [comment]
Hi,I run `./gradlew nativeImage`.but I get build/libs/vertio3-1.0-SNAPSHOT.jar.
it seems like executableName and outputDirectory not work.

**Comment by mike-neck** [comment]
The method `outputDirectory` is evaluated via Gradle's `Project#file(Object)`. The output binary is located under `/native-image`, which is located under root directory.

**Comment by zhoufeilongjava** [comment]
Thanks for your response!I solved it.
