### ISSUE TITLE
Support GraalVM 21.1

### ISSUE THREAD

**Issue by AlTech98** [mike-neck/graalvm-native-image-plugin#149]
Error:
`Cause: cannot found appropriate GraalVM version[java="16.0.1",graalvm="21.1.0",catalog="https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java16.properties|{ee=GraalVM Enterprise Edition}gds://oca.opensource.oracle.com/gds/meta-data.json"]
`

**Comment by mike-neck** [comment]
Sorry for inconvenient, the update will be available on v1.4.1 .
