### ISSUE TITLE
Add downloadTask for GraalVM

### ISSUE THREAD

**Issue by volyx** [mike-neck/graalvm-native-image-plugin#18]
Automatic download of GraalVM. It will be more convenient to run this plugin in Github Action for example.

Gradle palantir plugin supports this feature - https://github.com/palantir/gradle-graal/blob/develop/src/main/java/com/palantir/gradle/graal/DownloadGraalTask.java

Btw, thank you for the that awesome plugin!

**Comment by mike-neck** [comment]
For the use case of downloading GraalVM itself, please use [palantir/gradle-graal](https://github.com/palantir/gradle-graal). The purpose of this plugin is to offer a wrapper of installed GraalVM native image command.

**Comment by volyx** [comment]
Ok, thank you for plugin!
