### ISSUE TITLE
feature request: Install native-image component automatically

### ISSUE THREAD

**Issue by yujiorama** [mike-neck/graalvm-native-image-plugin#25]
## Summary

When GraalVM exists, install `native-image` component automatcally. 

## Detail

Execute command such as `gu install native-image` before running plugin Task to install `native-image` component.

Some configuration example.

```
nativeImage {
  graalVmHome = System.getProperty('java.home')
  installNativeImage = true
  mainClass = 'com.example.App'
  executableName = 'my-native-application'
  arguments(
      '--no-fallback',
      '--enable-all-security-services',
      '--initialize-at-run-time=com.example.runtime',
      '--report-unsupported-elements-at-runtime'
  )
}
```

**Comment by mike-neck** [comment]
Unfortunately I do not plan to fix this request.

This is because the goal of this tool is to provide a wrapper for the `native-image` command, and it is user's responsibility to install GraalVM and to run `gu install native-image`, which depends on the version of GraalVM(it's required after version 20.0.0), to install the `native-image` command.

**Comment by mike-neck** [comment]
I implemented the feature in PR #26.

In your requested feature, `installNativeImage` property seems redundant, so I did not give the property to the `nativeImage` block.

If there is no objection, I will merge #26 and release within a few days.

**Comment by mike-neck** [comment]
In PR #26, `nativeImage` task depends on `installNativeImage` task which invokes `gu install native-image` when `native-image` command does not exist.

https://github.com/mike-neck/graalvm-native-image-plugin/blob/e2f00eeb1089766204a668e7a90743f64569595a/src/main/java/org/mikeneck/graalvm/GraalvmNativeImagePlugin.java#L30

**Comment by yujiorama** [comment]
Thank you for your response. 👍 
I don't have any problem for you to proceed.
