### ISSUE TITLE
Type 'NativeImageTask': non-property method 'outputDirectory()' should not be annotated with: @OutputDirectory.

### ISSUE THREAD

**Issue by Zethson** [mike-neck/graalvm-native-image-plugin#36]
> Task :nativeImage
Type 'NativeImageTask': non-property method 'outputDirectory()' should not be annotated with: @OutputDirectory. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.4.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

Is the origin of this deprecation warning from your plugin? If yes, what can I do about it?

**Comment by mike-neck** [comment]
It's from graalvm-native-image-plugin. The user of this plugin has nothing to do with the warning, because it is for the `NativeImageTask` which declares non-getter(thus non-property) method as `@OutputDirectory`.

**Comment by Zethson** [comment]
So if I understood you correctly this should be improved in the plugin?

If yes, I would like to kindly request this to be improved.

Thanks!

**Comment by mike-neck** [comment]
As of version 0.6, these messages disappeared.

**Comment by Zethson** [comment]
Thank you!  Sunday, 28 June 2020, 09:05AM +02:00 from mike_neck  notifications@github.com :
