### ISSUE TITLE
run generateNativeImageConfig task with fail

### ISSUE THREAD

**Issue by letrungtrung** [mike-neck/graalvm-native-image-plugin#60]
generateNativeImageConfig {
    enabled = true
    byRunningApplication {
        stdIn("""
    |total: 2
    |contents:
    |  - name: foo
    |    size: 2052
    |""".stripMargin())
    }
    byRunningApplicationWithoutArguments()
    byRunningApplication {
        arguments('-h')
    }
}

After running generateNativeImageConfig  task, a fail throws like below
Execution failed for task ':mergeNativeImageConfig'.
> org.mikeneck.com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (VALUE_STRING), expected END_ARRAY: Unexpected JSON values; expected at most 1 properties (in JSON Array)
   at [Source: (BufferedReader); line: 2, column: 42] (through reference chain: org.mikeneck.graalvm.config.ProxyConfig[0])

**Comment by mike-neck** [comment]
Would you provide `proxy-config.json` files, generated in `build/tmp/native-image-config/out-n`(`n` = `0`, `1`, `2`), because it seems to have unexpected json shape.

**Comment by tasmalinakis** [comment]
Hi, I bumped into the same issue. Here's an example JSON of ProxyConfig:

`
[
  [
    "org.apache.http.conn.ConnectionRequest",
    "com.amazonaws.http.conn.Wrapped"
  ],
  [
    "org.apache.http.conn.HttpClientConnectionManager",
    "org.apache.http.pool.ConnPoolControl",
    "com.amazonaws.http.conn.Wrapped"
  ]
]
`

That should be valid though according to [documentation](https://www.graalvm.org/docs/Native-Image/user/DYNAMIC_PROXY)

**Comment by mike-neck** [comment]
Thanks.  With your information, I found the reason why `proxy-config.json` has the shape of an array of an array. I will fix this problem as follows.

- Making `ProxyUsage` class to extend `ArrayList<String>`.

**Comment by mike-neck** [comment]
Thank you for your report, this bug will be fixed in the next version(i.e. `v0.8.0`).
