### ISSUE TITLE
Support for native-image.properties ?

### ISSUE THREAD

**Issue by cmoine** [mike-neck/graalvm-native-image-plugin#78]
Is there any plan to support native-image.properties file, like the `native-image-maven-plugin` plugin?

More info described here: https://medium.com/graalvm/simplifying-native-image-generation-with-maven-plugin-and-embeddable-configuration-d5b283b92f57

The approach looks very elegant imho.

I can provide some help for the implementation if you want, (eventually a PR, but I don't have much time right now :-( )

**Comment by mike-neck** [comment]
Thank you for your feature request. And the link you wrote told me an addition of the feature `native-image.properties` to recent GraalVM.
Btw, when I tried this feature in my machine(GraalVM CE 20.2.0 Java 11), `native-image.properties` works well. Thus I won't do anything for the `native-image.properties` feature.
