### ISSUE TITLE
%GRAAL_HOME%\bin\native-image.cmd not found on Windows

### ISSUE THREAD

**Issue by remkop** [mike-neck/graalvm-native-image-plugin#8]
Thank you for your work on `graalvm-native-image-plugin`.

I used it successfully with Linux based projects but I am running into an issue on Windows:

```
> Task :nativeImage FAILED
native-image not found in graalVmHome(C:\java\graalvm-ce-java8-19.3.0.2)
```

This makes sense because in Windows (both for Java8 and Java11), the `native-image` generator script is called `native-image.cmd`, not `native-image`:

```
C:\java\graalvm-ce-java8-19.3.0.2>dir bin\native-image*

2019/12/20  00:08                71 native-image.cmd
               1 file                  71 bytes
```

Unfortunately the plugin searches only for `bin/native-image` and there is no way to configure a different path with either Gradle configuration or system properties, so the plugin cannot be used on Windows.

Can you please fall back to `bin/native-image.cmd` if  `bin/native-image` is not found, and ideally even make the full path to the native image generator configurable instead of (or in addition to) the GraalVM installation part?

(Note that the palantir plugin is still not ready for GraalVM 19.3+, so now is a good chance for your work to get more name recognition.)

Again thanks for making your work publicly available!

**Comment by mike-neck** [comment]
Thanks!

I Made some changes for Windows.

* fall back for native-image command.(If there is no `native-image` then the plugin will use `native-image.cmd` if available).
* Enclose parameters in double quote on Windows.

See #9 for more detail.

**Comment by remkop** [comment]
Thanks for your fast response!
I’d love to start using it; when might we expect a release?

**Comment by remkop** [comment]
Looks good, thank you!!
