### ISSUE TITLE
Allow usage without JAR task

### ISSUE THREAD

**Issue by lorenzleutgeb** [mike-neck/graalvm-native-image-plugin#93]
I was happily using your plugin. At some point the classpath I need for native image needed to differ from the classpath I need for "regularily" running my application. Therefore I created a new Gradle configuration, called it "nativeRuntimeClasspath" which extends from "runtimeClasspath" and excludes some dependencies. I wanted to avoid creating a second JAR only for it to be passed to `native-image`. However, it appears that this is not possible with your plugin as it always requires a JAR task.

The task I ended up with does not use your plugin anymore (using Gradle's Kotin DSL):

```gradle
configurations {
    create("nativeRuntimeClasspath") {
        extendsFrom(runtimeClasspath.get())

        dependencies {
            exclude(group = "com.example.a")
            exclude(group = "com.example.b")
        }
    }
}

tasks.create<Exec>("nativeImage") {
    dependsOn(tasks.compileJava)
    commandLine(
            "native-image",
            "--class-path=${project.configurations["nativeRuntimeClasspath"].asPath}:${sourceSets.main.get().output.asPath}",
            "--no-fallback",
            "--initialize-at-build-time=com.example.d.Foo",
            "--report-unsupported-elements-at-runtime",
            "-H:+ReportExceptionStackTraces",
            "-H:+TraceClassInitialization",
            "com.example.c.Main",
            "${project.buildDir}/native-image/${project.name}-${project.version}"
    )
}
```

Please consider allowing such setups with your plugin, i.e. allow passing a configuration as classpath for Native Image.

**Comment by mike-neck** [comment]
Thank you for using this plugin.

From your script, are you trying to configure as bellow?

```groovy
plugins {
  id 'java'
  id 'org.mikeneck.graalvm-native-image'
}
repositories {
  mavenCentral()
}

configurations {
  nativeRuntimeClasspath {
    extendsFrom (configurations.runtimeClasspath) {
      exclude(group: 'com.example.a')
      exclude(group: 'com.example.b')
    }
  }
}
nativeImage {
  // Not want to use Jar file.
  // In Groovy DSL it is able to configure this/Kotlin DSL not able.
  // Of course this will lead RuntimeException.
  jarTask = null

  // And want to add classes build from source sets.
  classes = sourceSets.main.output  // This API is not provided.

  // This API is currently available.
  runtimeClasspath = configurations. nativeRuntimeClasspath

  graalVmHome = System.getenv('JAVA_HOME')
  mainClass = 'com.example.d.Foo'
  executableName = "${project.name}-${project.version}"
  runtimeClasspath = configurations.app
  arguments(
    '--no-fallback',
    '-H:+TraceClassInitialization',
    '--initialize-at-build-time=com.example.Printer',
    '-H:+ReportExceptionStackTraces',
  )
}
```

**Comment by lorenzleutgeb** [comment]
I am not 100% sure, but yeah it goes in the right direction. I did not try to set `sourceSets.main.output` somewhere because it's not possible. I definitely would want to have `jarTask = null` (or some other "empty" value) and would like to specify the classpath for `native-image`. I am not entirely sure however, how the `runtimeClasspath` of your plugin fits into this, probably because I do not know enough about Gradle. If Gradle's `runtimeClasspath` contains all classes compiled from the sources of the project (IMO that would include `sourceSets.main.output`), then it should work out fine.

**Comment by mike-neck** [comment]
I did finally provide `classpath` property for users not wish to use `Jar` task to specify class path of an application.

https://github.com/mike-neck/graalvm-native-image-plugin/blob/7c133256f0cadbf51abd6c226cc7a95f597c2e10/src/functionalTest/resources/case93-without-jar-with-different-configuration/build-gradle.txt#L19-L31
